Test1-2/Test_1-2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('',include("todolist.urls")),
    path('admin/', admin.site.urls),
    path('todolist/', include("todolist.urls")),
    path('send_mail/', include("send_mail.urls")),
]

Test1-2/todolist/urls.py
from django.urls import path
from . import views

app_name = "todolist" # keep any name or app name
urlpatterns=[
    path("",views.index,name="index"),
    path("add",views.add,name="add"),
    path("remove",views.remove,name="remove"),
    path("edit",views.edit,name="edit"),
]

Test1-2/templates/edit.html
{% extends 'index.html' %}
{% block title %}Edit Data{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6" style="margin: 0 auto;">
      <form action="/update/{{id}}">
        <div class="form-group">
          <label for="title">Todo Title</label>
          <input type="text" class="form-control" id="title" name="title" value={{title}}>
        </div>
        <div class="form-group">
          <label for="description">Todo Description</label>
          <textarea class="form-control" id="description" name="description" rows="3">{{description}}</textarea>
        </div>
        <div class="form-group">
          <label for="priority">Todo Priority</label>
          <input type="number" class="form-control" id="priority" name="priority" value={{priority}}>
        </div>
        <button type="submit" class="btn btn-primary" style="margin: 0 auto;display: block;">Update</button>
      </form>
      </div>
      </div>
{% endblock %}

Test1-2/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Todo List</title>
  </head>
  <body>
    <h1>Todo List</h1>
    <ul>
      {% for task in tasks %}
         <li>{{task}}</li>
      {% endfor %}
   </ul>
   <div >
    <form action="{% url 'todolist:index' %}" method="POST">
      {% csrf_token %}
      {{form}}
      <button type="submit" name="button">Submit</button>
    </form>
    <form action="{% url 'todolist:clear' %}" method="POST">
      <button type="submit" name="clear">clear</button>
    </form>
    
      
   </div>
    
  </body>
</html>

Test1-2/templates/list.html
{% extends 'index.html' %}
{% block title %}All Todo's{% endblock %}
{% block content %}
{% for eachtodo in alltodos %}
<div class="row">
    <div class="col-md-6" style="margin:0 auto;">
        <div class="card container-fluid" style="margin-top: 1rem;">
            <div class="card-body">
              <h5 class="card-title">{{eachtodo.title}} {{eachtodo.priority}}</h5>
              <p class="card-text">{{eachtodo.description}}</p>
              <p class="card-text">{{eachtodo.created_at}}</p>
              
              <a href="/delete/{{eachtodo.id}}" class="btn btn-danger">Delete</a>
              <a href="/edit/{{eachtodo.id}}" class="btn btn-warning">Edit</a>


            </div>
          </div>
    </div>
</div>

{% endfor %}
{% endblock %}